<a href="https://colab.research.google.com/github/afolaba4success/Pytorch-Tutorial/blob/main/Intro_to_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2 + 2

4

In [ ]:
import torch

In [ ]:
!pip list

Package                            Version
---------------------------------- --------------------
absl-py                            1.4.0
accelerate                         1.2.1
aiohappyeyeballs                   2.4.4
aiohttp                            3.11.10
aiosignal                          1.3.2
alabaster                          1.0.0
albucore                           0.0.19
albumentations                     1.4.20
altair                             5.5.0
annotated-types                    0.7.0
anyio                              3.7.1
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.5.1
arviz                              0.20.0
astropy                            6.1.7
astropy-iers-data                  0.2024.12.16.0.35.48
astunparse                         1.6.3
async-timeout                      4.0.3
atpublic                           4.1.0
attrs                              24.3.0
audioread        

In [1]:
import torch
import numpy as np

**LISTS**

In [2]:
my_list = [1,2,4,3]
my_list

[1, 2, 4, 3]

**NUMPY ARRAY**

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.16048038, 0.33973823, 0.75042293, 0.50122626],
       [0.54817298, 0.92746015, 0.02156075, 0.85117695],
       [0.72848665, 0.82372798, 0.21376232, 0.37779582]])

In [4]:
np1.dtype

dtype('float64')

**TENSORS**

In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.7531, -0.6363,  0.1061, -1.8746],
        [ 0.3612,  0.1500, -0.2810,  0.4065],
        [-1.6163,  0.9494, -0.6924, -0.7862]])

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1605, 0.3397, 0.7504, 0.5012],
        [0.5482, 0.9275, 0.0216, 0.8512],
        [0.7285, 0.8237, 0.2138, 0.3778]], dtype=torch.float64)

In [8]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Reshape if we don't know the number of items using -1
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
# Slicing
my_torch7 = torch.arange(10)
my_torch7


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Grab an item
my_torch7[7]

tensor(7)

In [20]:
# Grab a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [21]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [24]:
# Return a column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [1]:
2 + 2

4

**MATH OPERATIONS**

In [3]:
import torch
import numpy as np

In [4]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,7])

In [5]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 11])

In [6]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 11])

In [8]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 3])

In [10]:
# Sun function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 3])

In [11]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 28])

In [12]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 28])

In [13]:
# Division
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 1.7500])

In [14]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 1.7500])

In [15]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 3])

In [16]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 3])

In [17]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 16384])

In [18]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 11])

In [19]:
# Reassignment_
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 11])

In [20]:
tensor_a

tensor([ 6,  8, 10, 11])

**Create a Basic Neural Network Model - Deep Learning with PyTorch5 for Irish Flower Dataset Classification**

In [26]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [28]:
# Create a Model Class that inherits nn.Module
class Model(nn.Module):
  # Input layer (4 features of the flower) -->
  # Hidder Layer1 (number of neurons) -->
  # H2 (n) -->
  # output (3 classes of irish flowers)
  def __init__(self, in_features=4, h1=8, h2=9, out_features = 3):
    super().__init__() # instantiate our nn.Module
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)

    return x

In [30]:
# Pick a manual seed for randomization
torch.manual_seed(41)

In [31]:
# Create an instance of the model
model = Model()